apiVersion: v1
kind: Service
metadata:
  name: app
  labels:
    app: app
spec:
  ports:
    - port: 80
      name: http
  clusterIP: None
  selector:
    app: app

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
  labels:
    app: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
        - name: app
          image: vaporio/ksync-example
          imagePullPolicy: Always

          resources:
            requests:
              cpu: 10m
          # resources

          ports:
            - name: http
              containerPort: 80
          #ports

          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          # env

          readinessProbe:
            httpGet:
              path: /
              port: 80
          # readinessProbe
        # app
      # containers
    # spec
  # template
# spec
