// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/ksync.proto

package proto_ksync

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import empty "github.com/golang/protobuf/ptypes/empty"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type SpecList struct {
	Items                map[string]*Spec `protobuf:"bytes,1,rep,name=items" json:"items,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *SpecList) Reset()         { *m = SpecList{} }
func (m *SpecList) String() string { return proto.CompactTextString(m) }
func (*SpecList) ProtoMessage()    {}
func (*SpecList) Descriptor() ([]byte, []int) {
	return fileDescriptor_ksync_ae47324ef8254a7d, []int{0}
}
func (m *SpecList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SpecList.Unmarshal(m, b)
}
func (m *SpecList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SpecList.Marshal(b, m, deterministic)
}
func (dst *SpecList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SpecList.Merge(dst, src)
}
func (m *SpecList) XXX_Size() int {
	return xxx_messageInfo_SpecList.Size(m)
}
func (m *SpecList) XXX_DiscardUnknown() {
	xxx_messageInfo_SpecList.DiscardUnknown(m)
}

var xxx_messageInfo_SpecList proto.InternalMessageInfo

func (m *SpecList) GetItems() map[string]*Spec {
	if m != nil {
		return m.Items
	}
	return nil
}

type Spec struct {
	Details              *SpecDetails `protobuf:"bytes,1,opt,name=details" json:"details,omitempty"`
	Services             *ServiceList `protobuf:"bytes,2,opt,name=services" json:"services,omitempty"`
	Status               string       `protobuf:"bytes,3,opt,name=status" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *Spec) Reset()         { *m = Spec{} }
func (m *Spec) String() string { return proto.CompactTextString(m) }
func (*Spec) ProtoMessage()    {}
func (*Spec) Descriptor() ([]byte, []int) {
	return fileDescriptor_ksync_ae47324ef8254a7d, []int{1}
}
func (m *Spec) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Spec.Unmarshal(m, b)
}
func (m *Spec) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Spec.Marshal(b, m, deterministic)
}
func (dst *Spec) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Spec.Merge(dst, src)
}
func (m *Spec) XXX_Size() int {
	return xxx_messageInfo_Spec.Size(m)
}
func (m *Spec) XXX_DiscardUnknown() {
	xxx_messageInfo_Spec.DiscardUnknown(m)
}

var xxx_messageInfo_Spec proto.InternalMessageInfo

func (m *Spec) GetDetails() *SpecDetails {
	if m != nil {
		return m.Details
	}
	return nil
}

func (m *Spec) GetServices() *ServiceList {
	if m != nil {
		return m.Services
	}
	return nil
}

func (m *Spec) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

type SpecDetails struct { // nolint: maligned
	Name                 string   `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	ContainerName        string   `protobuf:"bytes,2,opt,name=container_name,json=containerName" json:"container_name,omitempty"`
	PodName              string   `protobuf:"bytes,3,opt,name=pod_name,json=podName" json:"pod_name,omitempty"`
	Selector             string   `protobuf:"bytes,4,opt,name=selector" json:"selector,omitempty"`
	Namespace            string   `protobuf:"bytes,5,opt,name=namespace" json:"namespace,omitempty"`
	LocalPath            string   `protobuf:"bytes,6,opt,name=local_path,json=localPath" json:"local_path,omitempty"`
	RemotePath           string   `protobuf:"bytes,7,opt,name=remote_path,json=remotePath" json:"remote_path,omitempty"`
	Reload               bool     `protobuf:"varint,8,opt,name=reload" json:"reload,omitempty"`
	LocalReadOnly        bool     `protobuf:"varint,9,opt,name=local_read_only,json=localReadOnly" json:"local_read_only,omitempty"`
	RemoteReadOnly       bool     `protobuf:"varint,10,opt,name=remote_read_only,json=remoteReadOnly" json:"remote_read_only,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SpecDetails) Reset()         { *m = SpecDetails{} }
func (m *SpecDetails) String() string { return proto.CompactTextString(m) }
func (*SpecDetails) ProtoMessage()    {}
func (*SpecDetails) Descriptor() ([]byte, []int) {
	return fileDescriptor_ksync_ae47324ef8254a7d, []int{2}
}
func (m *SpecDetails) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SpecDetails.Unmarshal(m, b)
}
func (m *SpecDetails) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SpecDetails.Marshal(b, m, deterministic)
}
func (dst *SpecDetails) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SpecDetails.Merge(dst, src)
}
func (m *SpecDetails) XXX_Size() int {
	return xxx_messageInfo_SpecDetails.Size(m)
}
func (m *SpecDetails) XXX_DiscardUnknown() {
	xxx_messageInfo_SpecDetails.DiscardUnknown(m)
}

var xxx_messageInfo_SpecDetails proto.InternalMessageInfo

func (m *SpecDetails) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *SpecDetails) GetContainerName() string {
	if m != nil {
		return m.ContainerName
	}
	return ""
}

func (m *SpecDetails) GetPodName() string {
	if m != nil {
		return m.PodName
	}
	return ""
}

func (m *SpecDetails) GetSelector() string {
	if m != nil {
		return m.Selector
	}
	return ""
}

func (m *SpecDetails) GetNamespace() string {
	if m != nil {
		return m.Namespace
	}
	return ""
}

func (m *SpecDetails) GetLocalPath() string {
	if m != nil {
		return m.LocalPath
	}
	return ""
}

func (m *SpecDetails) GetRemotePath() string {
	if m != nil {
		return m.RemotePath
	}
	return ""
}

func (m *SpecDetails) GetReload() bool {
	if m != nil {
		return m.Reload
	}
	return false
}

func (m *SpecDetails) GetLocalReadOnly() bool {
	if m != nil {
		return m.LocalReadOnly
	}
	return false
}

func (m *SpecDetails) GetRemoteReadOnly() bool {
	if m != nil {
		return m.RemoteReadOnly
	}
	return false
}

type ServiceList struct {
	Items                []*Service `protobuf:"bytes,1,rep,name=items" json:"items,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *ServiceList) Reset()         { *m = ServiceList{} }
func (m *ServiceList) String() string { return proto.CompactTextString(m) }
func (*ServiceList) ProtoMessage()    {}
func (*ServiceList) Descriptor() ([]byte, []int) {
	return fileDescriptor_ksync_ae47324ef8254a7d, []int{3}
}
func (m *ServiceList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ServiceList.Unmarshal(m, b)
}
func (m *ServiceList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ServiceList.Marshal(b, m, deterministic)
}
func (dst *ServiceList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ServiceList.Merge(dst, src)
}
func (m *ServiceList) XXX_Size() int {
	return xxx_messageInfo_ServiceList.Size(m)
}
func (m *ServiceList) XXX_DiscardUnknown() {
	xxx_messageInfo_ServiceList.DiscardUnknown(m)
}

var xxx_messageInfo_ServiceList proto.InternalMessageInfo

func (m *ServiceList) GetItems() []*Service {
	if m != nil {
		return m.Items
	}
	return nil
}

type Service struct {
	SpecDetails          *SpecDetails     `protobuf:"bytes,1,opt,name=spec_details,json=specDetails" json:"spec_details,omitempty"`
	RemoteContainer      *RemoteContainer `protobuf:"bytes,2,opt,name=remote_container,json=remoteContainer" json:"remote_container,omitempty"`
	Status               string           `protobuf:"bytes,3,opt,name=status" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *Service) Reset()         { *m = Service{} }
func (m *Service) String() string { return proto.CompactTextString(m) }
func (*Service) ProtoMessage()    {}
func (*Service) Descriptor() ([]byte, []int) {
	return fileDescriptor_ksync_ae47324ef8254a7d, []int{4}
}
func (m *Service) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Service.Unmarshal(m, b)
}
func (m *Service) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Service.Marshal(b, m, deterministic)
}
func (dst *Service) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Service.Merge(dst, src)
}
func (m *Service) XXX_Size() int {
	return xxx_messageInfo_Service.Size(m)
}
func (m *Service) XXX_DiscardUnknown() {
	xxx_messageInfo_Service.DiscardUnknown(m)
}

var xxx_messageInfo_Service proto.InternalMessageInfo

func (m *Service) GetSpecDetails() *SpecDetails {
	if m != nil {
		return m.SpecDetails
	}
	return nil
}

func (m *Service) GetRemoteContainer() *RemoteContainer {
	if m != nil {
		return m.RemoteContainer
	}
	return nil
}

func (m *Service) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

type RemoteContainer struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	ContainerName        string   `protobuf:"bytes,2,opt,name=container_name,json=containerName" json:"container_name,omitempty"`
	NodeName             string   `protobuf:"bytes,3,opt,name=node_name,json=nodeName" json:"node_name,omitempty"`
	PodName              string   `protobuf:"bytes,4,opt,name=pod_name,json=podName" json:"pod_name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RemoteContainer) Reset()         { *m = RemoteContainer{} }
func (m *RemoteContainer) String() string { return proto.CompactTextString(m) }
func (*RemoteContainer) ProtoMessage()    {}
func (*RemoteContainer) Descriptor() ([]byte, []int) {
	return fileDescriptor_ksync_ae47324ef8254a7d, []int{5}
}
func (m *RemoteContainer) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RemoteContainer.Unmarshal(m, b)
}
func (m *RemoteContainer) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RemoteContainer.Marshal(b, m, deterministic)
}
func (dst *RemoteContainer) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RemoteContainer.Merge(dst, src)
}
func (m *RemoteContainer) XXX_Size() int {
	return xxx_messageInfo_RemoteContainer.Size(m)
}
func (m *RemoteContainer) XXX_DiscardUnknown() {
	xxx_messageInfo_RemoteContainer.DiscardUnknown(m)
}

var xxx_messageInfo_RemoteContainer proto.InternalMessageInfo

func (m *RemoteContainer) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *RemoteContainer) GetContainerName() string {
	if m != nil {
		return m.ContainerName
	}
	return ""
}

func (m *RemoteContainer) GetNodeName() string {
	if m != nil {
		return m.NodeName
	}
	return ""
}

func (m *RemoteContainer) GetPodName() string {
	if m != nil {
		return m.PodName
	}
	return ""
}

func init() {
	proto.RegisterType((*SpecList)(nil), "proto.ksync.SpecList")
	proto.RegisterMapType((map[string]*Spec)(nil), "proto.ksync.SpecList.ItemsEntry")
	proto.RegisterType((*Spec)(nil), "proto.ksync.Spec")
	proto.RegisterType((*SpecDetails)(nil), "proto.ksync.SpecDetails")
	proto.RegisterType((*ServiceList)(nil), "proto.ksync.ServiceList")
	proto.RegisterType((*Service)(nil), "proto.ksync.Service")
	proto.RegisterType((*RemoteContainer)(nil), "proto.ksync.RemoteContainer")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// KsyncClient is the client API for Ksync service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type KsyncClient interface {
	GetSpecList(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*SpecList, error)
}

type ksyncClient struct {
	cc *grpc.ClientConn
}

func NewKsyncClient(cc *grpc.ClientConn) KsyncClient {
	return &ksyncClient{cc}
}

func (c *ksyncClient) GetSpecList(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*SpecList, error) {
	out := new(SpecList)
	err := c.cc.Invoke(ctx, "/proto.ksync.Ksync/GetSpecList", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Ksync service

type KsyncServer interface {
	GetSpecList(context.Context, *empty.Empty) (*SpecList, error)
}

func RegisterKsyncServer(s *grpc.Server, srv KsyncServer) {
	s.RegisterService(&_Ksync_serviceDesc, srv)
}

func _Ksync_GetSpecList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KsyncServer).GetSpecList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.ksync.Ksync/GetSpecList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KsyncServer).GetSpecList(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

var _Ksync_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.ksync.Ksync",
	HandlerType: (*KsyncServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetSpecList",
			Handler:    _Ksync_GetSpecList_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/ksync.proto",
}

func init() { proto.RegisterFile("proto/ksync.proto", fileDescriptor_ksync_ae47324ef8254a7d) }

var fileDescriptor_ksync_ae47324ef8254a7d = []byte{
	// 535 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x94, 0x5d, 0x6f, 0xd3, 0x3e,
	0x14, 0xc6, 0xff, 0x49, 0xdf, 0xd2, 0x93, 0xff, 0xda, 0xcd, 0x82, 0x2a, 0x74, 0x43, 0x54, 0x91,
	0x80, 0x8a, 0x8b, 0x54, 0x2a, 0x08, 0xf1, 0x22, 0x71, 0x03, 0x53, 0x85, 0x86, 0x00, 0x85, 0x0f,
	0x50, 0x79, 0xc9, 0x61, 0x8b, 0x96, 0xc6, 0x51, 0xec, 0x4e, 0xca, 0x1d, 0x97, 0xdc, 0xf1, 0x31,
	0xf8, 0x28, 0x7c, 0x2d, 0xe4, 0xe3, 0x34, 0x4d, 0xd7, 0x21, 0xed, 0xaa, 0xf6, 0xf3, 0xfc, 0x7c,
	0x8e, 0x5d, 0x3f, 0x31, 0x1c, 0xe5, 0x85, 0x50, 0x62, 0x76, 0x25, 0xcb, 0x2c, 0x0a, 0x68, 0xcc,
	0x5c, 0xfa, 0x09, 0x48, 0x1a, 0x1f, 0x5f, 0x08, 0x71, 0x91, 0xe2, 0x8c, 0xb4, 0xf3, 0xf5, 0xf7,
	0x19, 0xae, 0x72, 0x55, 0x1a, 0xd2, 0xff, 0x65, 0x81, 0xf3, 0x2d, 0xc7, 0xe8, 0x53, 0x22, 0x15,
	0x7b, 0x09, 0x9d, 0x44, 0xe1, 0x4a, 0x7a, 0xd6, 0xa4, 0x35, 0x75, 0xe7, 0x93, 0xa0, 0x51, 0x26,
	0xd8, 0x50, 0xc1, 0x47, 0x8d, 0x9c, 0x66, 0xaa, 0x28, 0x43, 0x83, 0x8f, 0xcf, 0x00, 0xb6, 0x22,
	0x3b, 0x84, 0xd6, 0x15, 0x96, 0x9e, 0x35, 0xb1, 0xa6, 0xfd, 0x50, 0x0f, 0xd9, 0x53, 0xe8, 0x5c,
	0xf3, 0x74, 0x8d, 0x9e, 0x3d, 0xb1, 0xa6, 0xee, 0xfc, 0x68, 0xaf, 0x6e, 0x68, 0xfc, 0x37, 0xf6,
	0x2b, 0xcb, 0xff, 0x69, 0x41, 0x5b, 0x6b, 0x6c, 0x0e, 0xbd, 0x18, 0x15, 0x4f, 0x52, 0x49, 0xb5,
	0xdc, 0xb9, 0xb7, 0xb7, 0xee, 0x83, 0xf1, 0xc3, 0x0d, 0xc8, 0x5e, 0x80, 0x23, 0xb1, 0xb8, 0x4e,
	0x22, 0x94, 0x55, 0xb3, 0x1b, 0x8b, 0x8c, 0xa9, 0xcf, 0x11, 0xd6, 0x24, 0x1b, 0x41, 0x57, 0x2a,
	0xae, 0xd6, 0xd2, 0x6b, 0xd1, 0xa6, 0xab, 0x99, 0xff, 0xc7, 0x06, 0xb7, 0xd1, 0x86, 0x31, 0x68,
	0x67, 0x7c, 0x85, 0xd5, 0xd1, 0x68, 0xcc, 0x1e, 0xc3, 0x20, 0x12, 0x99, 0xe2, 0x49, 0x86, 0xc5,
	0x92, 0x5c, 0x9b, 0xdc, 0x83, 0x5a, 0xfd, 0xac, 0xb1, 0x07, 0xe0, 0xe4, 0x22, 0x36, 0x80, 0x69,
	0xd2, 0xcb, 0x45, 0x4c, 0xd6, 0x58, 0xef, 0x39, 0xc5, 0x48, 0x89, 0xc2, 0x6b, 0x93, 0x55, 0xcf,
	0xd9, 0x09, 0xf4, 0xf5, 0x12, 0x99, 0xf3, 0x08, 0xbd, 0x0e, 0x99, 0x5b, 0x81, 0x3d, 0x04, 0x48,
	0x45, 0xc4, 0xd3, 0x65, 0xce, 0xd5, 0xa5, 0xd7, 0x35, 0x36, 0x29, 0x5f, 0xb9, 0xba, 0x64, 0x8f,
	0xc0, 0x2d, 0x70, 0x25, 0x14, 0x1a, 0xbf, 0x47, 0x3e, 0x18, 0x89, 0x80, 0x11, 0x74, 0x0b, 0x4c,
	0x05, 0x8f, 0x3d, 0x67, 0x62, 0x4d, 0x9d, 0xb0, 0x9a, 0xb1, 0x27, 0x30, 0x34, 0x75, 0x0b, 0xe4,
	0xf1, 0x52, 0x64, 0x69, 0xe9, 0xf5, 0x09, 0x38, 0x20, 0x39, 0x44, 0x1e, 0x7f, 0xc9, 0xd2, 0x92,
	0x4d, 0xe1, 0xb0, 0x6a, 0xb0, 0x05, 0x81, 0xc0, 0x81, 0xd1, 0x37, 0xa4, 0xff, 0x1a, 0xdc, 0xc6,
	0x5f, 0xcf, 0x9e, 0xed, 0x06, 0xed, 0xde, 0x6d, 0x77, 0x54, 0x85, 0xcb, 0xff, 0x6d, 0x41, 0xaf,
	0x92, 0xd8, 0x5b, 0xf8, 0x5f, 0xe6, 0x18, 0x2d, 0xef, 0x9a, 0x0b, 0x57, 0x36, 0x6e, 0x6f, 0x51,
	0xef, 0xb6, 0xbe, 0x9a, 0x2a, 0x23, 0x27, 0x3b, 0x05, 0x42, 0x82, 0xde, 0x6f, 0x98, 0x70, 0x58,
	0xec, 0x0a, 0xff, 0x8c, 0xcb, 0x0f, 0x0b, 0x86, 0x37, 0x16, 0xb3, 0x01, 0xd8, 0x49, 0x5c, 0x05,
	0xc6, 0x4e, 0xe2, 0xbb, 0xc6, 0xe5, 0x18, 0xfa, 0x99, 0x88, 0xb1, 0x99, 0x17, 0x47, 0x0b, 0x7b,
	0x59, 0x6a, 0xef, 0x64, 0x69, 0xbe, 0x80, 0xce, 0x99, 0x3e, 0x04, 0x7b, 0x07, 0xee, 0x02, 0x55,
	0xfd, 0x65, 0x8f, 0x02, 0xf3, 0x08, 0x04, 0x9b, 0x47, 0x20, 0x38, 0xd5, 0x8f, 0xc0, 0xf8, 0xfe,
	0xad, 0x9f, 0xb8, 0xff, 0xdf, 0x79, 0x97, 0xf4, 0xe7, 0x7f, 0x03, 0x00, 0x00, 0xff, 0xff, 0x90,
	0xf4, 0x37, 0xbf, 0x5d, 0x04, 0x00, 0x00,
}
